"""
SOLVI - Log Engine: Audit Trail Parser
Dedicated parser for Elekta Clinical Audit Trail logs (AUDIT_TRAIL.TXT).
"""

import os
from collections import Counter
from typing import Optional, Dict, Any, List, Generator
from .base_parser import BaseLogParser, LogCategory, LogParseResult

COL_SPECS = [
    ("occurred", 0, 32),
    ("host", 32, 96),
    ("event_id", 96, 128),
    ("event_name", 128, 192),
    ("user_id", 192, 224),
    ("user_name", 224, 256),
    ("patient_key", 256, 288),
    ("patient_id", 288, 320),
    ("linac_id", 320, 352),
    ("linac_name", 352, 384),
]


class AuditTrailParser(BaseLogParser):
    """Parses fixed-width SQL Server clinical audit logs generated by Elekta Integrity."""

    @property
    def category(self) -> LogCategory:
        return LogCategory.AUDIT_TRAIL

    def can_parse(self, filename: str, sample_bytes: bytes) -> bool:
        lower = os.path.basename(filename).lower()
        if "audit_trail" in lower and lower.endswith(".txt"):
            return True
        sample_str = sample_bytes[:256].decode("utf-8", errors="replace")
        return "AUDIT_TRAIL_HOST_NAME" in sample_str and "RT_EVENT_ID" in sample_str

    def parse_line(self, line: str) -> Optional[Dict[str, str]]:
        """Parses a single line into a dictionary using fixed-width column boundaries."""
        if not line or len(line) < 32 or line.startswith("-") or line.startswith("OCCURRED"):
            return None
        record = {}
        for col_name, start, end in COL_SPECS:
            val = line[start:end].strip().strip('"') if len(line) >= start else ""
            record[col_name] = val
        if not record.get("occurred") or not record.get("event_name"):
            return None
        return record

    def stream_file(self, file_path: str) -> Generator[Dict[str, str], None, None]:
        """Memory-efficient streaming generator for large AUDIT_TRAIL files."""
        with open(file_path, "r", encoding="utf-8", errors="replace") as f:
            # Skip header lines
            f.readline()
            f.readline()
            for line in f:
                rec = self.parse_line(line.rstrip("\r\n"))
                if rec:
                    yield rec

    def parse_file(
        self,
        file_path: str,
        max_records: Optional[int] = 500,
        filter_event: Optional[str] = None,
        filter_user: Optional[str] = None,
        **kwargs
    ) -> LogParseResult:
        if not os.path.exists(file_path):
            return LogParseResult(
                success=False,
                category=self.category,
                source_name=os.path.basename(file_path),
                errors=[f"File not found: {file_path}"]
            )

        events: List[Dict[str, Any]] = []
        event_counter = Counter()
        user_counter = Counter()
        linac_id = ""
        linac_name = ""

        try:
            with open(file_path, "r", encoding="utf-8", errors="replace") as f:
                f.readline()  # Header line
                f.readline()  # Dashes separator
                
                count = 0
                for line in f:
                    rec = self.parse_line(line.rstrip("\r\n"))
                    if not rec:
                        continue
                    
                    ev_name = rec["event_name"]
                    u_name = rec["user_name"]
                    
                    event_counter[ev_name] += 1
                    if u_name:
                        user_counter[u_name] += 1
                    if not linac_id and rec.get("linac_id"):
                        linac_id = rec["linac_id"]
                    if not linac_name and rec.get("linac_name"):
                        linac_name = rec["linac_name"]

                    # Filter match
                    if filter_event and filter_event.lower() not in ev_name.lower():
                        continue
                    if filter_user and filter_user.lower() not in u_name.lower():
                        continue

                    if max_records is None or len(events) < max_records:
                        events.append(rec)
                    
                    count += 1
                    # Performance cutoff for full scan if max_records is small and no filter
                    if not filter_event and not filter_user and max_records and count >= max_records * 5:
                        break

            summary = {
                "total_events_sampled": count,
                "returned_events_count": len(events),
                "linac_id": linac_id or "4574",
                "linac_name": linac_name or "05Elekta",
                "top_events": dict(event_counter.most_common(8)),
                "top_users": dict(user_counter.most_common(5)),
                "linac_reset_count": event_counter.get("Select Machine State Linac Reset", 0),
                "service_pages_count": (
                    event_counter.get("Display Service Pages enter", 0) +
                    event_counter.get("Display Service Pages Exit", 0)
                ),
            }

            return LogParseResult(
                success=True,
                category=self.category,
                source_name=os.path.basename(file_path),
                metadata={"file_size_bytes": os.path.getsize(file_path)},
                summary=summary,
                events=events
            )
        except Exception as e:
            return LogParseResult(
                success=False,
                category=self.category,
                source_name=os.path.basename(file_path),
                errors=[f"Error parsing audit trail: {str(e)}"]
            )

    def parse_bytes(
        self,
        data: bytes,
        source_name: str = "AUDIT_TRAIL.TXT",
        max_records: Optional[int] = 500,
        **kwargs
    ) -> LogParseResult:
        try:
            content = data.decode("utf-8", errors="replace")
            lines = content.splitlines()
            events = []
            event_counter = Counter()

            for line in lines[2:]:
                rec = self.parse_line(line)
                if rec:
                    ev_name = rec["event_name"]
                    event_counter[ev_name] += 1
                    if max_records is None or len(events) < max_records:
                        events.append(rec)

            summary = {
                "returned_events_count": len(events),
                "top_events": dict(event_counter.most_common(8)),
                "linac_reset_count": event_counter.get("Select Machine State Linac Reset", 0),
            }
            return LogParseResult(
                success=True,
                category=self.category,
                source_name=source_name,
                metadata={"content_length": len(data)},
                summary=summary,
                events=events
            )
        except Exception as e:
            return LogParseResult(
                success=False,
                category=self.category,
                source_name=source_name,
                errors=[f"Error decoding audit bytes: {str(e)}"]
            )
